### ISSUE TITLE
Double pop-up when <React.StrictMode> is used

### ISSUE THREAD

**Issue by anmcn** [RyanNerd/react-new-improved-window#5]
In React 18, <React.StrictMode> renders twice when in dev mode to detect unintended side-effects:

https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

This results in the pop-up being created twice, which causes issues for some types of pop-up (OAuth).

**Comment by RyanNerd** [comment]
This is a known React issue that only happens in development builds. Details are [here](https://github.com/facebook/react/issues/12856).

**Comment by anmcn** [comment]
We're painfully aware of that - this change in React 18 has caused us nothing but grief. We've lost many days chasing down the obscure issues it has caused in third-party components. I understand why they made the change, but I think it will just drive people to stop using `<StrictMode>`, which is counter-productive.

**Comment by RyanNerd** [comment]
> We're painfully aware of that - this change in React 18 has caused us nothing but grief. We've lost many days chasing down the obscure issues it has caused in third-party components. I understand why they made the change, but I think it will just drive people to stop using , which is counter-productive.

I also spent countless hours chasing my tail on this one. For that reason and some other minor issues I don't use it anymore.
